version: '3.9'

services:
  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    command: npm start

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: npm run dev -- --host

  db:
    image: postgres:15
    container_name: todo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
